# Generated by Django 3.0.2 on 2020-02-11 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('blog_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(max_length=1000)),
                ('blog_date', models.DateField(auto_now=True)),
                ('blog_writer', models.CharField(max_length=300)),
                ('blog_tags', models.CharField(default='others', max_length=100)),
                ('blog_look', models.IntegerField(default=0)),
                ('blog_neirong', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=10)),
                ('user_email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Website',
            fields=[
                ('wesite_name', models.CharField(max_length=20)),
                ('website_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Commit',
            fields=[
                ('commit_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('commit_neirong', models.TextField()),
                ('commit_time', models.DateField(auto_now=True)),
                ('commit_blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Article')),
                ('commit_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.User')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='blog_website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Website'),
        ),
    ]
